app.factory('common', function(){
    return {
        translateDkDict : function() {
            return {
                'Atl':'ATL',
                'Bos':'BOS',
                'Bkn':'BRK',
                'Cha':'CHO',
                'Chi':'CHI',
                'Cle':'CLE',
                'Dal':'DAL',
                'Den':'DEN',
                'Det':'DET',
                'GS':'GSW',
                'Hou':'HOU',
                'Ind':'IND',
                'LAC':'LAC',
                'LAL':'LAL',
                'Mem':'MEM',
                'Mia':'MIA',
                'Mil':'MIL',
                'Min':'MIN',
                'NO':'NOP',
                'NY':'NYK',
                'OKC':'OKC',
                'Orl':'ORL',
                'Phi':'PHI',
                'Pho':'PHO',
                'Por':'POR',
                'Sac':'SAC',
                'SA':'SAS',
                'Tor':'TOR',
                'Uta':'UTA',
                'Was':'WAS'
            }
        },
        translateTeamNames : function() {
            return {
                'Atlanta Hawks': 'ATL',
                'Boston Celtics': 'BOS',
                'Brooklyn Nets': 'BRK',
                'Charlotte Hornets': 'CHO',
                'Chicago Bulls': 'CHI',
                'Cleveland Cavaliers': 'CLE',
                'Dallas Mavericks': 'DAL',
                'Denver Nuggets': 'DEN',
                'Detroit Pistons': 'DET',
                'Golden State Warriors': 'GSW',
                'Houston Rockets': 'HOU',
                'Indiana Pacers': 'IND',
                'Los Angeles Clippers': 'LAC',
                'Los Angeles Lakers': 'LAL',
                'Memphis Grizzlies': 'MEM',
                'Miami Heat': 'MIA',
                'Milwaukee Bucks': 'MIL',
                'Minnesota Timberwolves': 'MIN',
                'New Orleans Pelicans': 'NOP',
                'New York Knicks': 'NYK',
                'Oklahoma City Thunder': 'OKC',
                'Orlando Magic': 'ORL',
                'Philadelphia 76ers': 'PHI',
                'Phoenix Suns': 'PHO',
                'Portland Trail Blazers': 'POR',
                'Sacramento Kings': 'SAC',
                'San Antonio Spurs': 'SAS',
                'Toronto Raptors': 'TOR',
                'Utah Jazz': 'UTA',
                'Washington Wizards': 'WAS'
            }
        }
    };
});